gremlin:
  endpoint: localhost
  port: 8889
  username: /dbs/database/colls/collection
  password: password
  ssl-enabled: false
  telemetry-allowed: false
  serializer: GRAPHSON_V3
  max-content-length: 65536
